### ISSUE TITLE
1337x plugin not working?

### ISSUE THREAD

**Issue by gumpster2010** [v1k45/1337x-qBittorrent-search-plugin#3]
Hey v1k45 --

I noticed that my qBittorrent search isn't pulling up any results on 1337x even for searches that yield results online. Do you know if the plugin needs updating? I would love to search using my qBittorrent client.

Thanks!

**Comment by v1k45** [comment]
I just checked. It is indeed not pulling results. Probably 1337x change its HTML markup and caused the plugin to break. I'll push a fix to this in a day or two.

Thanks for reporting.

**Comment by gumpster2010** [comment]
Hey v1k45! Any progress? Lmk if I should reinstall.

**Comment by v1k45** [comment]
Ah, I'm sorry, I forgot about this. I'll fix it ASAP.

**Comment by v1k45** [comment]
Hey @gumpster2010 I tried reproducing it the issue you're talking about. The plugin works fine for me.

Maybe you're facing this because your IP address is being checked by Cloudflare first for DDOS protection?

The same plugin with the domain `1337x.st` does not work for me because I get Cloudflare's "Wait for 5 seconds" interstitial before actually loading the page.
